/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.SQLException;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jagam
 */
public class LoginWindow extends javax.swing.JDialog {

    /**
     * Creates new form LoginWindow
     * @param parent
     * @param modal
     */
    public LoginWindow( JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpass = new javax.swing.JTextField();
        txtip = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblpass = new javax.swing.JLabel();
        lblyser = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        lblmotorddbb = new javax.swing.JLabel();
        cbmotorddbb = new javax.swing.JComboBox();
        lblnamedb = new javax.swing.JLabel();
        txtnamedb = new javax.swing.JTextField();

        setLocation(new java.awt.Point(0, 0));

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        btnLogin.setText("Loggin");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblpass.setText("Contraseña");

        lblyser.setText("Usuario");

        lblip.setText("IP");

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        lblmotorddbb.setText("Motor BBDD");

        cbmotorddbb.setModel(getMotorsModel());
        cbmotorddbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmotorddbbActionPerformed(evt);
            }
        });

        lblnamedb.setText("Nombre BD");

        txtnamedb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamedbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblyser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblpass))
                    .addComponent(lblnamedb)
                    .addComponent(lblmotorddbb))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbmotorddbb, 0, 134, Short.MAX_VALUE)
                    .addComponent(txtip)
                    .addComponent(txtpass)
                    .addComponent(txtuser)
                    .addComponent(txtnamedb, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblyser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtip)
                    .addComponent(lblip, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnamedb)
                    .addComponent(txtnamedb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmotorddbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmotorddbb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void cbmotorddbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmotorddbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmotorddbbActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        user = txtuser.getText();
        pass = txtpass.getText();
        ip = txtip.getText();
        nameDB = txtnamedb.getText();
        motorDB = (DBClass)cbmotorddbb.getSelectedItem();
        
        if( user.isEmpty() || pass.isEmpty() || ip.isEmpty() || nameDB.isEmpty() )
            JOptionPane.showMessageDialog(this, "Todos los datos deben de ser introducidos para establecer una conexión");
        else{
            
            try{
                DBScheme scheme = new DBScheme(motorDB, ip, nameDB, user, pass);
                ((GetDataWindow)getParent()).setDb(scheme); // mientras esta linea exista no se puede iniciar el programa hasta que getDataWindow este completado
                setVisible(false);
                
            }catch( SQLException e ){
                JOptionPane.showMessageDialog(this, "Imposible conectar con la base de datos");
            }catch( Exception e ){
                System.err.println(e.getMessage());
            }
            /*
            - Creamos la ventana principal
            - Lanzamos el JDialog/JFrame de Login
            - nos devuelve el DBScheme
            - Actualizamos la ventana principal
            */
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtnamedbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamedbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamedbActionPerformed

    public static ComboBoxModel<DBClass> getMotorsModel(){
        return CB_MOTORS_MODEL;
    }
    
    private String user;
    private String pass;
    private String ip;
    private String nameDB;
    private DBClass motorDB;
    private static final ComboBoxModel<DBClass> CB_MOTORS_MODEL = new DBClassComboBoxModel();
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox cbmotorddbb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lblmotorddbb;
    private javax.swing.JLabel lblnamedb;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblyser;
    private javax.swing.JTextField txtip;
    private javax.swing.JTextField txtnamedb;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
